### Create Admin User
POST http://localhost:3000/api/register/admin
Content-Type: application/json


{
  "email": "admin@example.com",
  "password": "SecurePassword123",
  "firstName": "Admin",
  "lastName": "User"
}

