### Create Admin User
POST https://workshoptest.wailsalutem-foundation.com/auth/login
Content-Type: application/json


{
  "email": "admin@workshop.com",
  "password": "H3nf0#iHF@39",
  "firstName": "Admin",
  "lastName": "User"
}

